test: script.mdl lex.py main.py matrix.py mdl.py display.py draw.py gmath.py yacc.py
	python main.py script.mdl

clean:
	rm -f *pyc *out parsetab.py *~

clear:
	rm -f *pyc *out parsetab.py *~ *ppm *png anim/*ppm anim/*png *gif
